config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The user can see one apartment, coming from a QR code or otherwise
  resources :apartments, only: [:index, :show] do
   resources :bookmarks, only: [:create]
   resources :floor_plan_pictures, only: :create
  end
  # The user can see all of their bookmarks, bookmark an apartment, update or destroy a bookmark.
  # The show page is the chat window
  # Messages are nested, so that they belong to a specific chat
  resources :bookmarks, only: [:index, :update, :destroy, :show] do
    resources :messages, only: :create
  end

  # Setting edit to show up as bookmarks/:id/fit and have a fit prefix
  get 'bookmarks/:id/fit', to: 'bookmarks#edit', as: :fit

  # The user can see all of their items, create, update or destroy one item.
  resources :items, only: [:index, :create, :update, :destroy]

  # Namespace for agency representative (show all or one apartment, create, update or destro an apartment)
  namespace :agency do
    resources :apartments, only: [:index, :new, :create, :edit, :update, :destroy, :show]
    resources :bookmarks, only: :index
  end

  get 'agency/apartments/:id/save_qr_code', to: 'agency/apartments#save_qr_code', as: 'save_qr_code'
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :apartment
  has_one :agency, through: :apartment
  has_many :messages, dependent: :destroy

  def self.unread_count_for(agency)
    joins(:messages).where.not(messages: { user: agency }).where(apartment: agency.apartments_as_agency, messages: { status: "unread" }).distinct.count(:id)
  end

  def user_last_message
    messages.where.not(user: agency).order(created_at: :desc).first
  end
end

app/controllers/agency/bookmarks_controller.rb
class Agency::BookmarksController < ApplicationController
  def index
    @bookmarks = policy_scope([:agency, Bookmark]).select("bookmarks.*, messages.created_at").joins(:messages).order("messages.created_at desc").distinct("bookmarks.id")
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # Inserted a authorization policy in front of each method as a reminder.
  # When writing the method, put it before saving to the database.
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  def index
    @bookmarks = policy_scope(Bookmark)
    if params[:result].present?
      @bookmarks = @bookmarks.where(result: params[:result])
    end
  end

  def show
    authorize @bookmark
    @bookmark.messages.where.not(user: current_user).map(&:read!)
    @message = Message.new
  end

  def create
    @apartment = Apartment.find(params[:apartment_id])
    @bookmark = Bookmark.new
    @bookmark.apartment = @apartment
    @bookmark.user = current_user
    authorize @bookmark
    if @bookmark.save
      redirect_to bookmarks_path(@bookmarks)
      # added a notice to notify the user that the bookmark saved
      flash[:notice] = "Bookmark saved!"
    else
      render "apartments/show", status: :unprocessable_entity
    end
  end

  def edit
    authorize @bookmark
    @items = current_user.items
  end

  def update
    authorize @bookmark
    arrangement_json = request.body.read
    @bookmark.update(arrangement: arrangement_json, result: params[:result])
    if @bookmark.save
      # @bookmarks = policy_scope(Bookmark)
      # respond_to do |format|
      #   format.js { render :index }
      # end
      redirect_to bookmarks_path
      flash[:notice] = "Saved!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @bookmark
    @bookmark.destroy
    redirect_to bookmarks_path
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/views/bookmarks/edit.html.erb
<div class="container">
  <h1 class="my-3">Place your items in <%= @bookmark.apartment.name %>!</h1>
  <%# check if arrangement already exists, and load either arrangement or floor_plan %>
  <% if @bookmark.arrangement.present? %>
    <% file_to_load = @bookmark.arrangement %>
  <% else %>
    <% file_to_load = @bookmark.apartment.floor_plan %>
  <% end %>
  <div
    class="row justify-content-between"
    data-controller="load-canvas"
    data-load-canvas-json-value="<%= file_to_load %>"
  >
    <%# buttons for canvas control %>
    <div class="row justify-content-start">
      <%# <button
        data-action="click->load-canvas#delete"
        class="btn btn-outline-warning btn-sm mx-1"
        style="width: 15%"
        >
        Remove item
      </button> %>
      <%# save results of fitting via dropdown %>
      <div class="save-features">
        <%# label %>
        <%# <%= simple_form_for(@bookmark) do |f| %>
          <%# <%= f.input :result, %>
          <%# type: :select,
          label: "How's everything fit?",
          label_html: {class: "my-2"},
          collection: ["Good fit", "Tight fit", "Poor fit"],
          input_html: {data: {load_canvas_target: "result"}} %>
          <%# <% end %>
          <div>
            <%= link_to "Book an Appointment", bookmarks_path, class:"button-52 mb-3", style:"width: 15%; height: 91%;" %>
          </div>
        </div>
      </div>
      <%# canvas elements %>
      <canvas id="new-canvas"  class="col-8 my-4">
        <%# render canvas here %>
      </canvas>
      <%# items list menu %>
      <div class="col-4 container my-4" style="border: black; background: linear-gradient(180deg, #8ed7f2, #48b6de); overflow-y: scroll; height:98vh; border-radius:4px; width: 30rem; z-index:1;">
        <h3 class="mt-3">Click to add</h3>
        <div class="row justify-content-around align-items-center">
          <div class="col-6 text-center">
            <button
              data-action="click->load-canvas#save"
              data-arrangement="<%= @bookmark.arrangement%>"
              data-bookmark="<%= @bookmark.id %>"
              class="button-51"
              >
              Save
            </button>
          </div>
          <div class="col-6 text-center">
            <button
              data-action="click->load-canvas#clear"
              class="btn btn-outline-success btn-sm mt-3"
              style="width: 50%"
              >
              Start over
            </button>
          </div>
        </div>
        <div class="row justify-content-center">
          <% current_user.items.all.each do |item| %>
            <%# create cards for each item %>
            <div
            class="card col-4 my-3 mx-2 p-2 items-button align-items-center"
            id="fit-item"
            data-action="click->load-canvas#add"
              data-name="image-<%= item.name %>"
              data-length="<%= item.length %>"
              data-width="<%= item.width %>"
              >
              <img
              src="<%= image_path(item.image)%>"
              alt="<%= item.name %>"
              class= "image-item"
              id="image-<%= item.name %>"
              data-load-canvas-target="image-<%= item.name %>"
            >
                <%# <button
                class="fa-solid fa-circle-plus fa-xl add-item border-0"
                > %>
                <%# </button> %>
                <div class="card-body">
                  <h4 class="card-title text-center"><%= item.name %></h4>
                  <p class="card-text"><%= item.length %> cm² x <%= item.width %> cm²</p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/bookmarks/fit.html.erb
<div class="container">
  <h1>Place your items!</h1>
  <div class="row">
    <%# canvas elements %>
    <div class="col-8">
      <h2>Canvas goes here</h2>
      <p><%= @bookmark.arrangement %></p>
    </div>
    <%# items list menu %>
    <div class="col-4 container">
      <% currentUser.items.all.each do |item| %>
        <%# create cards for each item %>
        <div class="card col-5 my-3 mx-2" style="width: 18rem;">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= item.name %> x <%= item.quantity %></h5>
            <p class="card-text"><%= item.length %>cm² x <%= item.width %>cm²</p>
            <a href="#" class="btn btn-primary"></a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/index.html.erb
<%# <div class="container">
  <h1 class="my-2">My Saved Apartments</h1>
  <% if @bookmarks.any? %>
<%# filter via fitting result %>
<%# <div class="row justify-content-start">
      <div class="col-sm-8 my-3">
        <%= link_to "All Apartments", bookmarks_path, class: "btn btn-secondary" %>
<%# <%= link_to "Good fit", bookmarks_path(result: "Good fit"), class: "btn btn-secondary" %>
<%# <%= link_to "Tight fit", bookmarks_path(result: "Tight fit"), class: "btn btn-secondary" %>
<%# <%= link_to "Poor fit", bookmarks_path(result: "Poor fit"), class: "btn btn-secondary" %>
<%# </div>
    </div>
    <div class="card-flashy-book"> %>
<%# create individual cards here %>
<%# <% @bookmarks.each do |bookmark| %>
  <%# <div class="col-4 card-bmk-img">
          <%= cl_image_tag bookmark.apartment.photos.first.key %>
  <%# </div> %>
  <%# Apartment info %>
  <%# <div class="col-5 card-bmk-infos ms-2"> %>
  <%# <h1><%= bookmark.apartment.name</h1>  %>
  <%# <h2><i class="fa-solid fa-location-dot"></i> <%= bookmark.apartment.address</h2> %>
  <%# <p><%= bookmark.apartment.category</p> %>
  <%# <p>¥<%= bookmark.apartment.price.to_i/month</p>
          <p><%= bookmark.apartment.total_floorspace m²</p>
          <% if bookmark.comment.blank? %>
  <%# <p>add comment(update)</p> %>
  <%# <% else %>
  <%# <p><%= bookmark.comment | edit comment</p>
          <% end %>
  <%# </div>
        <div class="col-2 d-flex flex-column"> %>
  <%# set badge color depending on results and insert %>
  <%# from here %>
  <%# <% if bookmark.result == "Good fit" %>
  <%# <p class="badge rounded-pill text-white" style="background: green;"><%= bookmark.result</p>  %>
  <%# <% elsif bookmark.result == "Tight fit" %>
  <%# <p class="badge rounded-pill text-white" style="background: orange;"><%= bookmark.result</p>  %>
  <%# <% elsif bookmark.result == "Poor fit" || bookmark.result == "Bad fit"%>
  <%# <p class="badge rounded-pill text-white" style="background: red;"><%= bookmark.result</p>  %>
  <%# <% else %>
  <%# <p class="badge rounded-pill text-black bg-info"><%= bookmark.result</p> %>
  <%# <% end %>
  <%# links %>
  <%# <ul id="side-menu"> %>
  <%# <li> %>
  <%# <div class="side-menu__label">Delete home</div> %>
  <%# </li> %>
  <%# <li><%= link_to "", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-outline-secondary btn-sm my-2 fa-solid fa-trash-can" %>
  <%# </ul> %>
  <%# <ul id="side-menu"> %>
  <%# <li> %>
  <%# <div class="side-menu__label">View details</div> %>
  <%# </li> %>
  <%# <li><%= link_to "", apartment_path(bookmark.apartment), class:"btn btn-outline-secondary btn-sm my-2 fa-solid fa-circle-info"</li> %>
  <%# </ul> %>
  <%# <ul id="side-menu"> %>
  <%# <li> %>
  <%# <div class="side-menu__label">Contact realtor</div> %>
  <%# </li> %>
  <%# <li><%= link_to "", bookmark_path(bookmark), class:"btn btn-outline-secondary btn-sm my-2 fa-solid fa-envelope"</li> %>
  <%# </ul> %>
  <%# <ul id="side-menu"> %>
  <%# <li> %>
  <%# <div class="side-menu__label">Check your fit!</div> %>
  <%# </li> %>
  <%# <li><%= link_to "", fit_path(bookmark), class:"btn btn-outline-success btn-sm my-2 fa-solid fa-people-carry-box"</li>

<%# </ul> %>
  <%# </div> %>
  <%# <% end %>
  <%# <% else %>
  <%# <p class="my-5">You don't have any apartments saved yet!</p> %>
  <%# <% end %>
  <%# </div> %>
  <%# </div> %>
  <%# comment %>
  <%# comment %>
  <div class="container-fluid flashy-container">
    <h1 class="my-2">My Saved Apartments</h1>
    <% if @bookmarks.any? %>
      <%# filter via fitting result %>
      <%# <div class="row justify-content-start"> %>
      <%# <div class="col-sm-8 my-3"> %>
      <%# <%= link_to "All Apartments", bookmarks_path, class: "btn btn-secondary" %>
      <%# <%= link_to "Good fit", bookmarks_path(result: "Good fit"), class: "btn btn-secondary" %>
      <%# <%= link_to "Tight fit", bookmarks_path(result: "Tight fit"), class: "btn btn-secondary" %>
      <%# <%= link_to "Poor fit", bookmarks_path(result: "Poor fit"), class: "btn btn-secondary" %>
      <%# </div> %>
    </div>
    <%# create individual cards here %>
    <div class="row justify-content-center">
      <% @bookmarks.each do |bookmark| %>
        <div class="card-flashy-book col-6">
          <% if bookmark.apartment.photos.attached? %>
            <%=cl_image_tag bookmark.apartment.photos.first.key, class: "img-flashy-book" %>
          <% end %>
          <div>
            <h2><%= bookmark.apartment.name %> - <%= bookmark.apartment.category %></h2>
            <h3 style="opacity:0.6;"><i class="fa-solid fa-location-dot"></i> <%= bookmark.apartment.address %></h3>
            <p>
              Total floorspace: <%= bookmark.apartment.total_floorspace %> m²
            </p>
            <p>
              <strong>¥<%= bookmark.apartment.price.to_i %>/month</strong>
            </p>
            <%# <% if bookmark.comment.blank? %>
            <%# <p>add comment(update)</p> %>
            <%# <% else %>
            <%# <p><%= bookmark.comment | edit comment</p>  %>
            <%# <% end %>
            <%# <% if bookmark.result == "Good fit" %>
            <%# <p class="badge rounded-pill text-white" style="background: green;"><%= bookmark.result</p> %>
            <%# <% elsif bookmark.result == "Tight fit" %>
            <%# <p class="badge rounded-pill text-white" style="background: orange;"><%= bookmark.result</p> %>
            <%# <% elsif bookmark.result == "Poor fit" || bookmark.result == "Bad fit"%>
            <%# <p class="badge rounded-pill text-white" style="background: red;"><%= bookmark.result</p> %>
            <%# <% else %>
            <%# <p class="badge rounded-pill text-black bg-info"><%= bookmark.result</p> %>
            <%# <% end %>
            <button class="button-flashy-book">
              <%= link_to "Check your fit", fit_path(bookmark) %>
            </button>
            <div class="button-three-book">
              <button class="button-flashy-book-small">
                <%= link_to "", apartment_path(bookmark.apartment), class:"btn-sm my-2 fa-solid fa-circle-info" %>
              </button>
              <button class="button-flashy-book-small">
                <%= link_to "", bookmark_path(bookmark), class:"btn-sm my-2 fa-solid fa-envelope" %>
              </button>
              <button class="button-flashy-book-small">
                <%= link_to "", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn-sm my-2 fa-solid fa-trash-can" %>
              </button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="my-5">You don't have any apartments saved yet!</p>
  <% end %>
</div>

app/views/bookmarks/show.html.erb
<%# User-agency chat about a specific apartment %>
<div class="container chat" data-controller="bookmark-subscription" data-bookmark-subscription-bookmark-id-value=<%= @bookmark.id %>
  data-bookmark-subscription-current-user-id-value=<%= current_user.id %>>
  <h1>#<%= @bookmark.apartment.name %></h1>

  <div class="messages" data-bookmark-subscription-target="messages">
    <% @bookmark.messages.each do |message| %>
       <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>
  <%= simple_form_for [@bookmark, @message],
  html: { data: { action: "turbo:submit-end->bookmark-subscription#resetForm" }, class: "d-flex" } do |f| %>
    <%= f.input :content,
      label: false,
      placeholder: "Message about ##{@bookmark.apartment.name}",
      wrapper_html: {class: "flex-grow-1"} %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>
</div>