config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The user can see one apartment, coming from a QR code or otherwise
  resources :apartments, only: [:index, :show] do
   resources :bookmarks, only: [:create]
   resources :floor_plan_pictures, only: :create
  end
  # The user can see all of their bookmarks, bookmark an apartment, update or destroy a bookmark.
  # The show page is the chat window
  # Messages are nested, so that they belong to a specific chat
  resources :bookmarks, only: [:index, :update, :destroy, :show] do
    resources :messages, only: :create
  end

  # Setting edit to show up as bookmarks/:id/fit and have a fit prefix
  get 'bookmarks/:id/fit', to: 'bookmarks#edit', as: :fit

  # The user can see all of their items, create, update or destroy one item.
  resources :items, only: [:index, :create, :update, :destroy]

  # Namespace for agency representative (show all or one apartment, create, update or destro an apartment)
  namespace :agency do
    resources :apartments, only: [:index, :new, :create, :edit, :update, :destroy, :show]
    resources :bookmarks, only: :index
  end

  get 'agency/apartments/:id/save_qr_code', to: 'agency/apartments#save_qr_code', as: 'save_qr_code'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-2 flex-shrink-0 d-flex" style="text-align: center;">
        <%= link_to "/" do %>
          <%= image_tag "suitefitlogo2_small.png", class:"logo-image mt-3"%>
        <% end %>
      </div>
      <div class="col-6 border-start border-end" >
        <div class="footer-text">
          <h3>SuiteFit find your best fit!</h3>
          <p>Copyright © 2023 all rights reserved</p>
          <div class="icon-container-homepage text-center">
            <i class="fab fa-facebook fa-lg"></i>
            <i class="fab fa-instagram fa-lg"></i>
            <i class="fab fa-line fa-lg"></i>
          </div>
        </div>
      </div>
      <div class="col-4 text-center mt-3 ">
        <h3>About us</h3>
        <div class="">
          <div>
            <%= link_to "E-mail", root_path %> <i class="fa-solid fa-square-envelope fa-lg"></i>
          </div>
          <div>
            <%= link_to "Contact us", root_path %> <i class="fa-solid fa-phone fa-lg"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid row align-items-center">
    <%# Sidebar button %>
    <div class="col-4 d-flex justify-content-start">
      <%= render "shared/sidebar" %>
    </div>
    <%# Logo in the middle %>
    <div class="col-4 d-flex justify-content-center">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "suitefitlogo1_small.png"%>
      <% end %>
    </div>
    <%# Column to make even spaces in the navbar %>
    <div class="col-4 d-flex"></div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="container-fluid">
  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Hi <%= current_user.username %>!</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item active">
              <% if current_user && current_user.agency? %>
                <% link_to "My Apartments", agency_apartments_path, class: "nav-link" %>
              <% else %>
                <%= link_to "All Apartments", apartments_path, class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item active">
              <%# Button for apartments for Admin and button for Items for User %>
              <% if current_user && current_user.agency? %>
                <%= link_to "My Apartments", agency_apartments_path, class: "nav-link" %>
              <% else %>
                <%= link_to "My Items", items_path, class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%# Button for Add an apartment for Admin and button for My bookmarks for User %>
              <% if current_user && current_user.agency? %>
                <%= link_to "Add Apartment", new_agency_apartment_path, class: "nav-link" %>
              <% else %>
                <%= link_to "My Bookmarks", bookmarks_path, class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%# Button for the agency to see requests from users %>
              <% if current_user && current_user.agency? %>
                <%= link_to agency_bookmarks_path, class: "nav-link" do %>
                  Requests <span class="request-counter" data-requests-subscription-target="requestsSidebar"><%= Bookmark.unread_count_for(current_user) %></span>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
            </li>
          <% else %>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
              <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
              <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                  <ul class="navbar-nav me-auto">
                    <%# Button for Home for all users%>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                    </li>
                  <% end %>
                </ul>
                <%# Here was dropdown , link just testing %>
              </ul>
            </div>
          </div>
        </div>