config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The user can see one apartment, coming from a QR code or otherwise
  resources :apartments, only: [:index, :show] do
   resources :bookmarks, only: [:create]
   resources :floor_plan_pictures, only: :create
  end
  # The user can see all of their bookmarks, bookmark an apartment, update or destroy a bookmark.
  # The show page is the chat window
  # Messages are nested, so that they belong to a specific chat
  resources :bookmarks, only: [:index, :update, :destroy, :show] do
    resources :messages, only: :create
  end

  # Setting edit to show up as bookmarks/:id/fit and have a fit prefix
  get 'bookmarks/:id/fit', to: 'bookmarks#edit', as: :fit

  # The user can see all of their items, create, update or destroy one item.
  resources :items, only: [:index, :create, :update, :destroy]

  # Namespace for agency representative (show all or one apartment, create, update or destro an apartment)
  namespace :agency do
    resources :apartments, only: [:index, :new, :create, :edit, :update, :destroy, :show]
    resources :bookmarks, only: :index
  end

  get 'agency/apartments/:id/save_qr_code', to: 'agency/apartments#save_qr_code', as: 'save_qr_code'
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :agency, class_name: "User"
  has_one :floor_plan_picture
  has_many :bookmarks
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true
  validates :total_floorspace, presence: true, numericality: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :category, presence: true, format: { with: /\A\d{1}\w{1,3}\z/ }
end

app/controllers/agency/apartments_controller.rb
require "rqrcode"
require 'chunky_png'

class Agency::ApartmentsController < ApplicationController
  # Inserted a authorization policy in front of each method as a reminder.
  # When writing the method, put it before saving to the database.
  before_action :set_apartment, only: [:show, :update, :destroy, :edit, :save_qr_code]

  def save_qr_code
    authorize([:agency, @apartment])
    url = "https://www.suitefit.tech/apartments/#{@apartment.id}"
    png = RQRCode::QRCode.new(url).as_png(
      module_px_size: 24,
      size: 480
    )
    send_data png, filename: "#{@apartment.name}_qr_code.png", type: 'image/png'
  end

  def index
    @apartments = policy_scope([:agency, Apartment])
    # sending the total amount of bookmarks and impressions to the view for stats
    @bookmarks_count = @apartments.map { |apt| apt.bookmarks.count }.sum
    @impressions_count = @apartments.map(&:impression_counter).sum
  end

  def show
    if @apartment.geocoded?
      @marker = {
        lat: @apartment.latitude,
        lng: @apartment.longitude,
        marker_html: render_to_string(partial: "apartments/marker")
      }
    end
    authorize([:agency, @apartment])
    @floor_plan_picture = FloorPlanPicture.new
  end

  def new
    @apartment = Apartment.new
    authorize([:agency, @apartment])
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.agency = current_user

    # attaching a qr code
    url = "https://www.suitefit.tech/apartments/#{@apartment.id}"
    qr_code = RQRCode::QRCode.new(url)
    @apartment.qr_code = qr_code

    authorize([:agency, @apartment])
    if @apartment.save
      redirect_to agency_apartment_path(@apartment)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize([:agency, @apartment])
  end

  def update
    @apartment.update(apartment_params)
    authorize([:agency, @apartment])

    if @apartment.save
      redirect_to agency_apartment_path(@apartment)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize([:agency, @apartment])

    Bookmark.where(apartment_id: @apartment.id).destroy_all
    @apartment.destroy
    redirect_to agency_apartments_path, status: :see_other
  end

  private

  def set_apartment
    @apartment = Apartment.find(params[:id])
  end

  def apartment_params
    params.require(:apartment).permit(:name, :description, :price, :total_floorspace, :address, :category, :floor_plan, photos: [])
  end
end

app/controllers/agency/bookmarks_controller.rb
class Agency::BookmarksController < ApplicationController
  def index
    @bookmarks = policy_scope([:agency, Bookmark]).select("bookmarks.*, messages.created_at").joins(:messages).order("messages.created_at desc").distinct("bookmarks.id")
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  # Inserted a authorization policy in front of each method as a reminder.
  # When writing the method, put it before saving to the database.
  skip_before_action :authenticate_user!, only: :show

  def index
    @apartments = policy_scope(Apartment)
  end

  def show
    @bookmark = Bookmark.new
    @apartment = Apartment.find(params[:id])
    # creating a marker for the map
    if @apartment.geocoded?
      @marker = {
        lat: @apartment.latitude,
        lng: @apartment.longitude,
        marker_html: render_to_string(partial: "marker")
      }
    end
    authorize @apartment
    increment_impression!(@apartment)
  end

  private

  # counting page views
  def increment_impression!(apartment)
    if user_signed_in? == false || !current_user.agency
      apartment.impression_counter += 1
      apartment.save
    end
  end
end

app/views/agency/apartments/edit.html.erb
<% if params[:floor_plan] == 'true' %>
  <div class="container" data-controller="apartment-canvas" data-apartment-canvas-floorplan-url-value=<%= @apartment.floor_plan_picture.photo.url %> data-apartment-canvas-id-value=<%= @apartment.id %>>
    <h1 class="my-2">Floor Plan Editor</h1>
    <button class="btn btn-secondary" data-apartment-canvas-target="drawButton" data-action="click->apartment-canvas#startDrawing">Start Drawing</button>
    <div class="d-none" data-apartment-canvas-target="saveButton">
      <button class="btn btn-secondary" data-action="click->apartment-canvas#setDoor">Set Main Door</button>
      <%= simple_form_for @apartment, url: agency_apartment_path(@apartment), html: {data: {'apartment-canvas-target': "saveFloorplan", action: 'turbo:submit-end->apartment-canvas#saveFloorplan'}} do |f| %>
        <%= f.input :floor_plan, as: :hidden, input_html: { data: {'apartment-canvas-target': "input" }}%>
        <%= f.submit "Save", class: "btn btn-secondary" %>
      <% end %>
    </div>
    <div class="canvas-container">
      <canvas id="new-canvas" class="border" data-apartment-canvas-target="canvas"></canvas>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-4">
        <h1 class="form-title">Edit an apartment</h1>
        <div class="form-shared">
          <%= simple_form_for @apartment, url: agency_apartment_path(@apartment), method: :patch do |f| %>
            <%= f.input :name %>
            <%= f.input :description, as: :text %>
            <%= f.input :price, label: "Rent (¥ per month)" %>
            <%= f.input :total_floorspace, label: "Total floorspace (m²)" %>
            <%= f.input :category %>
            <%= f.input :address %>
            <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Upload photos of your apartment" %>
            <%= f.input :creation, as: :hidden, input_html: { value: 'true'} %>
            <%= f.button :submit, "Save", class:"btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/agency/apartments/index.html.erb
<div class="container-fluid flashy-container">
  <h1 class="agency-index">Listed Apartments (<%= @apartments.count %>)</h1>
  <% if @apartments.any? %>
    <%# create individual cards here %>
    <div class="row justify-content-center">
      <% @apartments.each do |apartment| %>
        <div class="card-flashy-agency col-6">
          <%= link_to "", edit_agency_apartment_path(apartment), class: "fa-solid fa-pen flashy-edit-button" %>
          <% if apartment.photos.attached? %>
            <%= image_tag(apartment.photos[0], class: "img-flashy-agency") %>
          <% end %>
          <div>
            <h2><%= apartment.name %> - <%= apartment.category %></h2>
            <h3 style="opacity:0.6;"><i class="fa-solid fa-location-dot"></i> <%= apartment.address %></h3>
            <p>
              Total floorspace: <%= apartment.total_floorspace %> m²
            </p>
            <p>
              <strong>¥<%= apartment.price.to_i %>/month</strong>
            </p>
            <%# display individual stats %>
            <div class="row stats-number">
              <div class="col">
                <h5><strong><%= apartment.impression_counter %></strong></h5>
              </div>
              <div class="col">
                <h5><strong><%= apartment.bookmarks.count %></strong></h5>
              </div>
            </div>
            <div class="row stats-title">
              <div class="col">
                <p>Views</p>
              </div>
              <div class="col">
                <p>Bookmarks</p>
              </div>
            </div>
            <button class="button-flashy-agency">
              <%= link_to "View apartment", agency_apartment_path(apartment)%>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="my-4">No apartments are currently listed!</p>
  <% end %>
</div>

app/views/agency/apartments/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <h1 class="form-title">List an apartment</h1>
      <div class="form-shared" data-controller="new-forms">
        <%= simple_form_for @apartment, url: agency_apartments_path do |f| %>
          <%= f.input :name, placeholder: "Meguro Heights" %>
          <%= f.input :description, as: :text, placeholder: "A quiet place in the middle of the big city." %>
          <%= f.input :price, label: "Rent (¥ per month)", placeholder: "70000" %>
          <%= f.input :total_floorspace, label: "Total floorspace (m²)", placeholder: "20" %>
          <%= f.input :category, placeholder: "1LDK" %>
          <%= f.input :address, placeholder: "Tokyo, Meguro, 1-2-3" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, required: true, label: "Upload photos of your apartment" %>
          <%= f.button :submit, "Save", class:"btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/agency/apartments/show.html.erb
<% content_for :meta_title, "#{@apartment.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @apartment.description %>
<% if @apartment&.photos.attached? %>
  <% content_for :meta_image, cl_image_path(@apartment.photos[0].key) %>
<% end %>
<div class="container flashy-container-show">
  <div class="row" style="display: flex;">
    <div class="card-flashy-show col-7">
      <%= render "apartments/carousel", apartment: @apartment %>
      <%#= image_tag(@apartment.photos[0], class: "img-flashy") %>
      <%= link_to "", edit_agency_apartment_path(@apartment), class: "fa-solid fa-pen flashy-edit-button-agency-show" %>
      <%= link_to "", agency_apartment_path(@apartment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "fa-solid fa-trash flashy-delete-button-agency-show" %>
      <div class="row">
        <div class="g-col-6 text-center" style="position: relative;">
          <h2><%= @apartment.name %> - <%= @apartment.category %></h2>
          <h3 style="opacity:0.6"><i class="fa-solid fa-location-dot"></i> <%= @apartment.address %></h3>
          <%# Apartments description %>
          <p class="text-muted text-start"><%= @apartment.description %></p>
          <%# Apartments info %>
          <p><strong> Total floorspace: <%= @apartment.total_floorspace %> m²</strong> </p>
          <p><strong> ¥<%= @apartment.price.to_i %>/month</strong></p>
          <p><strong>Managed by <%= @apartment.agency.username %></strong></p>
        </div>
        <div class="justify-content-between align-items-center d-flex">
          <%# floor plan display %>
          <% if @apartment&.floor_plan_picture&.photo&.attached? %>
            <%= image_tag(@apartment.floor_plan_picture.photo, class: "show-floor-plan col-6 text-end my-2") %>
          <% else %>
            <div class="d-flex flex-column justify-content-center align-items-center">
              <span style="font-size: 15px">You haven't uploaded a floor plan yet!</span>
              <!-- Button trigger modal -->
              <button class="button-flashy w-75 my-2" style="color: black; display: inline;" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Upload Floor Plan
              </button>
            </div>
          <% end %>
          <div class="col-6">
            <div id="qr" class="my-2">
              <%# displaying the qr code %>
              <% @qr = RQRCode::QRCode.new("https://suite-fit-rlmp44-5e8ff51180b0.herokuapp.com/apartments/#{@apartment.id}") %>
              <%== @qr.as_svg(module_size: 4, viewbox: true) %>
            </div>
          </div>
        </div>
        <%# buttons row %>
        <div class="my-4 d-flex justify-content-around">
          <% if @apartment.floor_plan_picture.present? %>
            <div class="col">
              <%= link_to "Floor Plan Editor", edit_agency_apartment_path(@apartment, floor_plan: "true"), class: "button-flashy", style: "color: black;" %>
            </div>
          <% else %>
            <%# modal start %>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Upload floor plan</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= simple_form_for [@apartment, @floor_plan_picture], url: apartment_floor_plan_pictures_path(@apartment) do |f| %>
                      <%= f.input :photo, as: :file, label: "Upload the floor plan of your apartment" %>
                    </div>
                    <div class="modal-footer">
                      <%= f.button :submit, "Save", class:"button-flashy", style: "color: black;" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <%# modal end %>
          <% end %>
          <div class="col">
            <%= link_to save_qr_code_path(@apartment), class: "button-flashy", style: "color: black;" do %>
              <i class="fa-solid fa-download"></i>Save QR code
            <% end %>
          </div>
        </div>
        <%# display stats %>
        <div class="stats mt-4">
          <div class="row stats-number">
            <div class="col">
              <h5><strong><%= @apartment.impression_counter %></strong></h5>
            </div>
            <div class="col">
              <h5><strong><%= @apartment.bookmarks.count %></strong></h5>
            </div>
          </div>
          <div class="row stats-title">
            <div class="col">
              <p>Views</p>
            </div>
            <div class="col">
              <p>Bookmarks</p>
            </div>
          </div>
        </div>
        <%# end of stats %>
      </div>
    </div>
    <%# map %>
    <div class="col-5 container map">
      <div style="width: 100%; height: 100vh; position: sticky; top: 0;"
        data-controller="map"
        data-map-marker-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>