config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The user can see one apartment, coming from a QR code or otherwise
  resources :apartments, only: [:index, :show] do
   resources :bookmarks, only: [:create]
   resources :floor_plan_pictures, only: :create
  end
  # The user can see all of their bookmarks, bookmark an apartment, update or destroy a bookmark.
  # The show page is the chat window
  # Messages are nested, so that they belong to a specific chat
  resources :bookmarks, only: [:index, :update, :destroy, :show] do
    resources :messages, only: :create
  end

  # Setting edit to show up as bookmarks/:id/fit and have a fit prefix
  get 'bookmarks/:id/fit', to: 'bookmarks#edit', as: :fit

  # The user can see all of their items, create, update or destroy one item.
  resources :items, only: [:index, :create, :update, :destroy]

  # Namespace for agency representative (show all or one apartment, create, update or destro an apartment)
  namespace :agency do
    resources :apartments, only: [:index, :new, :create, :edit, :update, :destroy, :show]
    resources :bookmarks, only: :index
  end

  get 'agency/apartments/:id/save_qr_code', to: 'agency/apartments#save_qr_code', as: 'save_qr_code'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :length, presence: true
  validates :width, presence: true
  # validates :quantity, presence: true

  ITEMTYPES = ["Table", "Chair", "Armchair", "Couch", "Sofa", "Single bed", "Double bed", "Fridge", "Washing machine", "TV", "Wardrobe", "Microwave", "Trash can", "Basket", "Desk"]

  def image
    case self.name.downcase
    when "table" then "items/Circle-table.png"
    when "chair" then "items/Chair.png"
    when "armchair" then "items/Armchair.png"
    when "couch" then "items/Couch.png"
    when "sofa" then "items/Sofa.png"
    when "single bed" then "items/Single-bed.png"
    when "double bed" then "items/Double-bed.png"
    when "fridge" then "items/Fridge.png"
    when "washing machine" then "items/Washing machine.png"
    when "tv" then "items/Tv.png"
    when "wardrobe" then "items/Wardrobe.png"
    when "microwave" then "items/Microwave.png"
    when "trash can" then "items/Trash can.png"
    when "basket" then "items/Basket.png"
    when "desk" then "items/Desk.png"

    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # Inserted a authorization policy in front of each method as a reminder.
  # When writing the method, put it before saving to the database.
  def index
    @bookmark = Bookmark.all
    @item = Item.new
    @items = policy_scope(Item)
  end

  def create
    @items = policy_scope(Item)

    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item
    if @item.save
      redirect_to items_path
    else
      @pop_up = true
      render :index, status: :unprocessable_entity
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      redirect_to items_path
    else
      render :index, status: :unprocessable_entity
    end
    authorize @item
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:name, :length, :width, :photo, :quantity)
  end
end

app/views/items/_delete_item.html.erb
<%= link_to "Delete", item_path(item),
data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
class:"btn btn-outline-danger btn-sm pt-3" %>

app/views/items/_fields.html.erb
 <%= simple_form_for(item) do |f| %>
  <%= f.input :name, type: :select, collection: Item::ITEMTYPES %>
  <%= f.input :length, label: "Length (cm)" %>
  <%= f.input :width, label: "Width (cm)" %>
  <%# <%= f.input :quantity %>
  <div class="modal-footer justify-content-between">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/items/_item_form.html.erb
<!-- Button trigger modal -->
<button type="button" class="button-52" data-bs-toggle="modal" data-bs-target="#<%= new ? "item_new" : "item_#{item.id}_update" %>">
  <%= new ? "Add Item" : "Edit" %>
</button>
<!-- Modal -->
<div class="modal fade" id="<%= new ? "item_new" : "item_#{item.id}_update" %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="<%= item %>" aria-labelledby="staticBackdropLabel"data-create-item-popup-target="modal" data-popup="<%= popup == true %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel"><%= new ? "Add Item" : "Edit #{item.name}" %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" data-create-item-popup-target="form">
        <%= render "fields", item: item, style:"z-index: 1;" %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="row justify-content-between align-items-center">
    <div class="col-6">
      <h1 class="my-2">My Items</h1>
    </div>
    <%# form for item %>
    <div class="col-6 d-flex justify-content-end" data-controller="create-item-popup">
      <%= render "item_form", item: @item, new: true, popup: @pop_up %>
    </div>
  </div>
  <%# create individual cards here %>
  <div class="d-flex justify-content-center">
    <div style="border: black; background: linear-gradient(180deg, #8ed7f2, #48b6de);border-radius:4px; width: 160vh; margin-bottom:15px; margin-top:15px;">
      <div class="row justify-content-center">
        <% @items.each do |item| %>
          <div class="card col-4 my-3 mx-2 p-2 align-items-center"
            id="fit-img">
            <div class="justify-content-around">
              <%# Photo for item %>
              <div class="text-center">
                <img src="<%= image_path(item.image)%>" alt="<%= item.name %>" class= "image-item"
              id="image-<%= item.name %>">
              </div>
              <div class="card-body text-center">
                <h2 class="card-title"><%= item.name %></h2>
                <p class="card-text">Length: <%= item.length %></p>
                <p class="card-text">Width: <%= item.width %></p>
              </div>
              <div class="d-flex gap-2 mb-2">
                <%= render "delete_item", item: item %>
                <%= render "item_form", item: item, new: false, popup: false %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>